#!/usr/bin/env bash
# 阶段 1：show 只读命令（契约 §1.1 全量）。
set -u
source "$(cd "$(dirname "$0")" && pwd)/cli-fulltest-lib.sh"

echo "############ 阶段 1：show 只读命令 ############"
{ echo "############ 阶段 1：show 只读命令 ############"; } >> "$LOG"

run S1 "show version"
run S1 "show system uptime"
run S1 "show system cpu"
run S1 "show system memory"
run S1 "show system storage"
run S1 "show system hugepages"
run S1 "show system kernel"
run S1 "show system hardware"
run S1 "show system core-dumps"
run S1 "show system tech-support"
run S1 "show system configuration sessions"
run S1 "show interfaces"
run S1 "show interfaces physical"
run S1 "show interfaces management"
run S1 "show virtual-switches"
run S1 "show vrfs"
run S1 "show acls"
run S1 "show nat"
run S1 "show port-mirroring"
run S1 "show qos policies"
run S1 "show vpp"
run S1 "show vpp threads"
run S1 "show vpp runtime"
run S1 "show vpp buffers"
run S1 "show vpp memory"
run S1 "show vpp capture"
run S1 "show bonds"
run S1 "show lldp neighbors"
run S1 "show protocols lldp neighbors"
run S1 "show virtual-machine-functions"
run S1 "show container-functions"
run S1 "show images"
run S1 "show resource-pools"
run S1 "show alarms"
run S1 "show alarms all"
run S1 "show log system"
run S1 "show log audit"
run S1 "show users"
# 活动会话清单（决策 #301）：正向内容断言——表头必须在，否则「无活动会话」这类空答会被算作通过
# （本条命令由 CLI 自己发起，调用方本身就是一个会话 ⇒ 必然至少一行）。
expect_out S1 "Token-ID" "show system api tokens"
run S1 "show configuration"
run S1 "show configuration history"
run S1 "show tech-support"
run S1 "help"

summary "阶段 1"
