package schema

// 配置模式命令树（提示符 nfvis#，全部 S；class 授权到节点，§2）。
// 内容对应《NFViS-CLI命令树完整设计》§2.1~§2.9。
//
// 语句树（ConfigPathTree）描述 set/delete 语句的路径语法：实例参数（Param）
// 入路径、取值叶子（Value）不入路径——与 AGENTS.md「参数节点双重语义」一致。
// set/delete/show/edit 各挂载一份独立构建的语句树（父指针互不干扰）。
func ConfigRoot() *Node {
	pathChildren := func() []*Node { return ConfigPathTree().Children }
	root := K("", "root",
		Su(K("set", "设置配置语句", pathChildren()...)),
		Su(K("delete", "删除配置语句/子树", pathChildren()...)),
		Su(K("show", "显示 candidate（当前层级）", pathChildren()...)),
		Su(K("annotate", "为配置节点添加注释（FR-CFG-007）", pathChildren()...)),
		Su(K("edit", "进入层级", pathChildren()...)),
		Su(K("up", "返回上一级")),
		Su(K("top", "返回顶层")),
		Su(K("commit", "提交 candidate（FR-CFG-002/003）",
			K("confirmed", "超时未确认自动回滚（默认 10 分钟，FR-CFG-003）",
				Opt(V("uint", "确认等待分钟数")),
			),
			K("check", "仅校验不下发（FR-CFG-002）"),
			K("and-quit", "提交成功后退出配置模式"),
		)),
		Su(K("rollback", "取历史快照为 candidate（需再 commit，FR-CFG-005）",
			Opt(P("<n>", "快照编号（缺省 1）", DynRevisions)),
		)),
		Su(K("load", "JSON 配置导入（FR-CFG-008）",
			K("override", "整体替换 candidate", V("path", "JSON 文件路径")),
			K("merge", "增量合并 candidate", V("path", "JSON 文件路径")),
		)),
		Su(K("save", "candidate 导出 JSON（FR-CFG-008）", V("path", "JSON 文件路径"))),
		Su(K("run", "配置模式内执行操作命令", operChildren()...)),
		Su(K("discard", "丢弃 candidate 并释放会话锁")),
		Su(K("exit", "退出配置模式（有未提交变更时提示确认）")),
	)
	finalize(root, nil)
	return root
}

// operChildren 操作树子节点（run 命令复用；操作树权限位不适用于 run 场景，
// 执行仍经操作模式鉴权）。
func operChildren() []*Node {
	return OperRoot().Children
}

// ConfigPathTree 配置语句路径树（每次调用独立构建；set/delete/show/edit
// 各挂载独立实例，父指针互不干扰）。
func ConfigPathTree() *Node {
	root := K("", "root",
		// —— system（§2.2，FR-SYS-001/004/011/012/013、FR-SEC-003/008）——
		K("system", "系统配置",
			K("hostname", "主机名", V("string", "名称")),
			K("timezone", "时区", V("string", "如 Asia/Shanghai")),
			K("ntp", "NTP（FR-SYS-001）",
				K("server", "NTP 服务器",
					P("<ip|host>", "服务器地址", ""),
					K("prefer", "标记首选"),
				),
			),
			K("dns", "DNS",
				K("server", "DNS 服务器",
					SPA("<ip>", "dns_servers", "服务器地址"),
					K("secondary", "备用服务器", SPA("<ip>", "dns_servers", "地址")),
				),
			),
			K("api", "API 服务（FR-SYS-006）",
				K("port", "HTTPS 端口（默认 443）", V("uint", "端口")),
				K("token-ttl-minutes", "Token 有效期（默认 60）", V("uint", "分钟")),
				K("max-sessions", "并发连接上限", V("uint", "个数")),
				K("tls", "TLS 证书（FR-SYS-011）",
					K("cert-file", "证书文件（PEM）", V("path", "路径")),
					K("key-file", "私钥文件（PEM）", V("path", "路径")),
					K("self-signed", "自签证书",
						K("regenerate", "重签自签证书"),
					),
				),
			),
			K("management", "管理口（FR-SYS-001，变更受 FR-CFG-012 自锁保护）",
				K("interface", "管理网卡（内核驱动；不得用于数据面，FR-NET-002/FR-SEC-001）",
					SPD("<ifname>", "interface", "管理网卡（内核驱动）", DynKernelIfnames)),
				K("ip", "管理口 IP",
					K("address", "静态地址（IPv4/IPv6）", V("ip-prefix", "如 192.168.1.10/24")),
				),
				K("gateway", "默认网关", V("ip", "网关地址")),
			),
			K("kernel", "内核启动基线（FR-SYS-014；大页/隔离核由 resource-pools 派生）",
				K("nmi-watchdog", "NMI watchdog（VPP 场景通常关闭）", VE("bool", "开关", "true", "false")),
				K("transparent-hugepages", "透明大页策略", VE("thp", "策略", "always", "madvise", "never")),
				K("iommu", "IOMMU 模式", VE("iommu", "模式", "on", "off", "pt")),
				K("tuned-profile", "tuned 性能档", V("name", "档位名（如 nfvis-throughput）")),
				K("params", "附加内核参数（逃生口，可多条）", SPA("<param>", "params", "内核参数")),
			),
			K("health", "硬件健康（FR-SYS-012）",
				K("thresholds", "告警阈值",
					K("cpu-temp-celsius", "CPU 温度阈值", V("uint", "摄氏度")),
					K("disk-temp-celsius", "磁盘温度阈值", V("uint", "摄氏度")),
					K("disk-used-percent", "磁盘使用率阈值", V("uint", "百分比")),
				),
			),
			K("syslog", "日志（FR-SYS-004/013）",
				K("host", "远程 syslog（RFC 5424）",
					P("<ip>", "目标地址", ""),
					Opt(K("port", "目标端口", V("uint", "端口"))),
					Opt(K("facility", "facility", V("facility", "如 daemon"))),
					Opt(K("severity", "级别", VE("severity", "级别", "debug", "info", "warn", "error"))),
				),
				K("local", "本地日志",
					K("level", "日志级别", VE("level", "级别", "debug", "info", "warn", "error")),
					K("retention-days", "保留天数（FR-SYS-013）", V("uint", "天")),
					K("max-size-mb", "容量上限（滚动覆盖）", V("uint", "MB")),
				),
			),
			K("login", "本地用户与 class（FR-SEC-003）",
				K("user", "本地用户",
					P("<name>", "用户名", ""),
					K("password", "口令（加盐哈希存储）", V("string", "口令")),
					K("class", "归属 class", SP("<class-name>", "class", "class 名")),
				),
				K("class", "自定义 class",
					P("<name>", "class 名", DynClasses,
						K("allow", "允许的命令树节点", V("command-path", "命令路径")),
						K("deny", "拒绝的命令树节点", V("command-path", "命令路径")),
					),
				),
				K("password-policy", "口令策略",
					K("min-length", "最小长度", V("uint", "字符")),
					K("complexity", "复杂度要求", VE("bool", "开关", "true", "false")),
					K("expire-days", "有效期", V("uint", "天")),
					K("lockout-threshold", "连续失败锁定阈值", V("uint", "次数")),
					K("lockout-minutes", "锁定时长", V("uint", "分钟")),
				),
			),
			K("idle-timeout-minutes", "CLI 会话空闲超时（默认 10，FR-SEC-005）", V("uint", "分钟")),
		),

		// —— protocols（§2.2b，FR-NET-018）——
		K("protocols", "顶级协议层级",
			K("lldp", "LLDP 邻居发现",
				K("enable", "全局启停", VE("bool", "开关", "true", "false")),
				K("advertisement-interval", "通告间隔（默认 30s）", V("uint", "秒")),
				K("interface", "按接口覆盖",
					P("<ifname>", "接口名", DynVppIfnames,
						K("enable", "启停", VE("bool", "开关", "true", "false")),
					),
				),
			),
		),

		// —— interfaces / bonds（§2.3，FR-NET-003/004/017）——
		K("interfaces", "物理网卡",
			P("<ifname>", "接口名", DynVppIfnames,
				K("description", "描述", V("string", "文本")),
				K("disable", "禁用接口"),
				K("mtu", "MTU", V("uint", "字节数")),
				K("sriov", "SR-IOV（FR-NET-004）",
					K("vf-count", "创建/回收 VF 数量", V("uint", "数量")),
				),
				K("ingress-policy", "入向限速策略绑定（§2.5）", P("<name>", "策略名", DynQos)),
			),
		),
		K("bonds", "链路聚合（FR-NET-017，bond 名可如物理口般引用）",
			P("<name>", "bond 名", "",
				K("members", "成员物理口（须未被虚拟交换机引用）",
					Opt(PT("<seq>", "uint", "成员序号")),
					SPA("<ifname>", "members", "接口名"),
				),
				K("lacp", "LACP（缺省静态聚合）",
					K("mode", "LACP 模式",
						VE("mode", "active|passive", "active", "passive"),
						Opt(K("interval", "报文间隔", VE("interval", "fast|slow", "fast", "slow"))),
					),
					K("disable", "关闭 LACP（转静态聚合）"),
				),
				K("mtu", "MTU", V("uint", "字节数")),
				K("description", "描述", V("string", "文本")),
			),
		),

		// —— virtual-switches（§2.4，FR-NET-010~015）——
		K("virtual-switches", "虚拟交换机（L2=bridge-domain，L3=VRF，附录 B）",
			P("<name>", "虚拟交换机名", DynVSwitches,
				K("type", "类型（创建后不可改）", VE("type", "l2|l3", "l2", "l3")),
				K("vlan", "VLAN（仅 L2）",
					K("access", "交换机级默认 untag VLAN", V("vlan", "1-4094")),
				),
				K("gateway", "BVI 三层网关（仅 L2，FR-NET-014）",
					K("ip", "网关地址（IPv4/IPv6 可多条）", V("ip-prefix", "如 192.168.100.1/24")),
					K("vrf", "所属 VRF（缺省专属 VRF vr-<交换机名>）", SP("<name>", "vrf", "VRF 名")),
					K("acl-in", "入向 ACL", SP("<acl>", "acl_in", "ACL 名")),
					K("acl-out", "出向 ACL", SP("<acl>", "acl_out", "ACL 名")),
				),
				K("ports", "成员端口",
					PT("<seq>", "uint", "端口序号",
						K("interface", "物理口/bond 成员",
							SP("<ifname>", "interface", "接口名"),
							Opt(K("trunk", "trunk 模式",
								K("vlans", "tagged VID 列表", V("vlan-list", "如 100,200"))),
							),
							Opt(K("native", "trunk native VLAN", V("vlan", "1-4094"))),
						),
						K("vnf", "VM vhost-user 口成员",
							P("<vm-name>", "VNF 名", DynVMs,
								K("interface", "vNIC 名",
									SP("<vnic-name>", "vnf_interface", "vNIC 名"),
									Opt(K("trunk", "trunk 模式",
										K("vlans", "tagged VID 列表", V("vlan-list", "如 100,200"))),
									),
								),
							),
						),
						K("container", "容器 memif 口成员",
							P("<ct-name>", "容器名", DynContainers,
								K("interface", "vNIC 名", SP("<vnic-name>", "container_interface", "vNIC 名")),
							),
						),
					),
				),
				K("cross-connect", "两端口直通模式（与 ports/gateway 互斥，FR-NET-012）",
					P("<port-a>", "端口 A 序号", ""),
					P("<port-b>", "端口 B 序号", ""),
				),
				K("l3-interface", "三层接口（仅 L3，FR-NET-013）",
					P("<ifname|vlan>", "物理口/bond 或 vlan <v>", DynVppIfnames,
						K("ip", "IP 配置",
							K("address", "地址（IPv4/IPv6 可多条）", V("ip-prefix", "如 10.10.0.1/24")),
						),
						K("acl-in", "入向 ACL 绑定（§2.5）", P("<acl>", "ACL 名", DynAcls)),
					),
				),
				K("static-routes", "静态路由（仅 L3，IPv4/IPv6）",
					P("<prefix>", "目的网段", "",
						K("next-hop", "下一跳", V("ip", "地址")),
						K("distance", "管理距离（默认 1）", V("uint", "0-255")),
					),
					K("default", "默认路由",
						K("next-hop", "下一跳", V("ip", "地址")),
					),
				),
			),
		),

		// —— 高级网络功能（§2.5）——
		K("acls", "ACL（五元组+动作，VPP acl plugin）",
			P("<name>", "ACL 名", DynAcls,
				K("rule", "规则（按 seq 排序生效）",
					PT("<seq>", "uint", "规则序号",
						K("source", "源地址", V("ip-prefix|any", "ip-prefix 或 any")),
						K("destination", "目的地址", V("ip-prefix|any", "ip-prefix 或 any")),
						K("protocol", "协议", VE("protocol", "协议", "tcp", "udp", "icmp", "any")),
						Opt(K("source-port", "源端口", V("port|range", "如 80 或 1024-65535"))),
						Opt(K("destination-port", "目的端口", V("port|range", "如 80 或 1024-65535"))),
						K("action", "动作", VE("action", "permit|deny", "permit", "deny")),
						K("direction", "方向", VE("direction", "ingress|egress", "ingress", "egress")),
					),
				),
			),
		),
		K("nat", "NAT44（仅作用于 L3 交换机，VPP nat44 plugin）",
			K("source-pool", "源地址池",
				P("<name>", "池名", "",
					K("address-range", "地址范围",
						V("ip", "起始 IP"),
						K("to", "至", V("ip", "结束 IP")),
					),
				),
			),
			K("rules", "转换规则",
				PT("<seq>", "uint", "规则序号",
					K("match", "匹配条件",
						K("source", "源网段",
							V("ip-prefix", "如 192.168.100.0/24"),
							K("virtual-switch", "作用 L3 交换机", SP("<name>", "virtual_switch", "交换机名")),
						),
					),
					K("action", "转换动作",
						K("source-pool", "使用地址池（出接口另需 action interface，必填）", SP("<name>", "source_pool", "池名")),
						K("interface", "直接出接口", SP("<ifname>", "interface", "接口名")),
					),
				),
			),
			K("static", "1:1 静态发布",
				P("<inside-ip>", "内部 IP", "",
					K("to", "映射到外部 IP", P("<outside-ip>", "外部 IP", "")),
				),
			),
		),
		K("port-mirroring", "端口镜像（VPP span）",
			P("<name>", "会话名", "",
				K("source", "源端口",
					K("interface", "物理口源",
						SP("<ifname>", "interface", "接口名"),
						K("direction", "复制方向", VE("direction", "ingress|egress|both", "ingress", "egress", "both")),
					),
					K("vnf", "VNF vNIC 源",
						P("<vm>", "VNF 名", DynVMs,
							K("interface", "vNIC 名",
								SP("<vnic>", "vnf_interface", "vNIC 名"),
								K("direction", "复制方向", VE("direction", "ingress|egress|both", "ingress", "egress", "both")),
							),
						),
					),
				),
				K("analyzer", "分析端口",
					K("interface", "分析口（物理口）", SP("<ifname>", "interface", "接口名")),
				),
			),
		),
		K("qos", "限速（VPP policer，CIR/CBS）",
			K("policies", "限速策略",
				P("<name>", "策略名", DynQos,
					K("cir", "承诺信息速率", V("uint", "bps")),
					K("cbs", "承诺突发尺寸", V("uint", "bytes")),
				),
			),
		),

		// —— resource-pools（§2.6，FR-CMP-001/005、FR-SYS-002/003）——
		K("resource-pools", "全局资源池（变更需 reboot，commit 时提示）",
			K("hugepages", "大页内存池",
				IV(K("page-size", "页大小（与 vpp memory hugepage-preference 一致，FR-SYS-010）",
					VE("size", "2M|1G", "2M", "1G"),
					K("count", "页数量", V("uint", "数量")),
				)),
			),
			K("cpu", "隔离核",
				K("isolated-cores", "隔离核列表（如 \"4-15\"）", V("core-list", "如 4-15")),
				K("numa", "NUMA 亲和声明",
					K("node", "NUMA 节点号",
						PT("<node>", "uint", "节点号",
							K("cores", "该节点核列表", V("core-list", "如 4-7")),
						),
					),
				),
			),
		),

		// —— vpp（§2.9，FR-SYS-008/009/010）——
		K("vpp", "VPP 数据面运行时配置（生成 startup.conf，cpu/memory/dpdk 变更需重启数据面）",
			K("cpu", "线程绑核（核须在隔离核池内，FR-SYS-010）",
				K("main-core", "主线程绑核", V("uint", "核号")),
				K("corelist-workers", "worker 核列表（如 \"5,7,9-11\"）", V("core-list", "如 5,7")),
				K("workers-per-numa", "按 NUMA 分配 worker（与 corelist-workers 互斥）", V("uint", "个数")),
			),
			K("memory", "内存",
				K("main-heap-size", "主堆大小（默认 1G）", V("size", "如 1G")),
				K("buffers-per-numa", "每 NUMA buffer 数（默认 16385）", V("uint", "个数")),
				K("hugepage-preference", "大页偏好（须与资源池页大小一致）", VE("size", "2M|1G", "2M", "1G")),
			),
			K("dpdk", "DPDK 设备参数（全局默认 + 单网卡覆盖两级，决策 #18）",
				K("dev", "队列/描述符",
					K("rx-queues", "收队列数（全局默认）", V("uint", "个数")),
					K("tx-queues", "发队列数（全局默认）", V("uint", "个数")),
					K("rx-descriptors", "收描述符（全局默认）", V("uint", "个数")),
					K("tx-descriptors", "发描述符（全局默认）", V("uint", "个数")),
					P("<ifname>", "单网卡覆盖（须为 DPDK 物理口，FR-CFG-011⑧）", DynVppIfnames,
						K("rx-queues", "收队列数", V("uint", "个数")),
						K("tx-queues", "发队列数", V("uint", "个数")),
						K("rx-descriptors", "收描述符", V("uint", "个数")),
						K("tx-descriptors", "发描述符", V("uint", "个数")),
					),
				),
				K("uio-driver", "UIO 驱动（安装器默认 vfio-pci）", VE("driver", "驱动", "vfio-pci", "igb-uio")),
			),
			K("plugins", "插件开关（acl/nat/span/dpdk/linux-cp...）",
				P("<name>", "插件名", DynVppPlugins,
					K("state", "启用状态", VE("state", "enable|disable", "enable", "disable")),
				),
			),
		),

		// —— virtual-machine-functions（§2.7，FR-CMP-010~019）——
		K("virtual-machine-functions", "VM VNF",
			P("<name>", "VNF 名", DynVMs,
				K("image", "镜像（vm-image）", SP("<image-name>", "image", "镜像名")),
				K("vcpu", "vCPU（从隔离核池分配）",
					K("count", "数量", V("uint", "个数")),
					Opt(K("pin", "绑核（默认 true）", VE("bool", "开关", "true", "false"))),
				),
				K("memory", "内存",
					K("size-mb", "大小（从大页池分配）", V("uint", "MB")),
					K("hugepage-size", "页大小（默认资源池主池，FR-CMP-019）", VE("size", "2M|1G", "2M", "1G")),
					K("numa", "NUMA 亲和",
						K("node", "节点号（与 vcpu NUMA 一致）", V("uint", "节点号")),
					),
					K("backing", "内存类型（normal 禁止 vhost-user vNIC，FR-CFG-011①）",
						VE("type", "hugepage|normal", "hugepage", "normal"),
					),
				),
				K("disks", "附加数据盘（virtio，FR-CMP-018）",
					P("<disk-name>", "盘名", "",
						K("size-gb", "空盘容量（与 image 二选一）", V("uint", "GB")),
						K("image", "从 vm-image 克隆创建", SP("<image-name>", "image", "镜像名")),
					),
				),
				K("interfaces", "vNIC",
					P("<vnic-name>", "vNIC 名", "",
						K("type", "接入类型", VE("type", "vhost-user|sriov-vf", "vhost-user", "sriov-vf")),
						K("sriov", "SR-IOV 直通（FR-NET-021）",
							K("physical-interface", "物理口",
								SP("<ifname>", "physical_interface", "接口名"),
								K("vf", "VF 编号", V("uint", "VF ID")),
							),
						),
						K("mac", "MAC（缺省自动生成）", V("mac", "地址")),
						K("vlan", "VLAN tag", V("vlan", "1-4094")),
						K("virtual-switch", "所属 L2 交换机（sriov-vf 时仅登记）",
							SPD("<name>", "virtual_switch", "交换机名", DynVSwitches),
						),
					),
				),
				K("cloud-init", "初始化注入（FR-CMP-016）",
					K("user-data", "user-data（YAML 文本或文件）", V("string", "内容/路径")),
					K("ssh-key", "SSH 公钥（可多条）", SPA("<key>", "ssh_keys", "公钥")),
					K("hostname", "guest 主机名", V("string", "名称")),
				),
				K("serial", "串口",
					K("console", "串口控制台",
						K("enable", "启用（默认启用，FR-CMP-014）"),
					),
				),
				K("autostart", "随系统自启", VE("bool", "开关", "true", "false")),
				K("description", "描述", V("string", "文本")),
			),
		),

		// —— container-functions（§2.8，FR-CMP-020~022）——
		K("container-functions", "容器 VNF（Docker + memif，FR-NET-022）",
			P("<name>", "容器名", DynContainers,
				K("image", "镜像（container-image）", SP("<image-name>", "image", "镜像名")),
				K("vcpu", "vCPU 限制（cgroup）",
					K("count", "数量", V("uint", "个数")),
				),
				K("memory", "内存限制（cgroup）",
					K("size-mb", "大小", V("uint", "MB")),
				),
				K("interfaces", "memif vNIC",
					P("<vnic-name>", "vNIC 名", "",
						K("type", "接入类型", VE("type", "memif", "memif")),
						K("virtual-switch", "所属 L2 交换机", SPD("<name>", "virtual_switch", "交换机名", DynVSwitches)),
						Opt(K("mac", "MAC", V("mac", "地址"))),
						Opt(K("vlan", "VLAN tag", V("vlan", "1-4094"))),
					),
				),
				K("env", "环境变量（可多条）",
					PT("<key>", "name", "变量名", V("string", "值")),
				),
				K("command", "入口命令", V("string", "命令")),
				K("args", "命令参数", V("string", "参数")),
				K("restart-policy", "重启策略（FR-CMP-022）", VE("policy", "no|on-failure", "no", "on-failure")),
				K("autostart", "随系统自启", VE("bool", "开关", "true", "false")),
				K("description", "描述", V("string", "文本")),
			),
		),
	)
	finalize(root, nil)
	return root
}
