package schema

// 操作模式命令树（提示符 nfvis>）。
// 内容对应《NFViS-CLI命令树完整设计》§1——show/request/其余操作命令，
// 权限按 §4 预置 class 矩阵：show 全 R；request 生命周期/镜像/接口 O；
// request 破坏性动作（software/reboot/configuration/zeroize 等）与
// clear/start shell 为 S。
func OperRoot() *Node {
	root := K("", "root",
		K("show", "显示系统状态与配置",
			K("version", "版本汇总（nfvis/ubuntu/vpp/dpdk/libvirt/qemu/docker）"),
			K("system", "系统信息",
				K("uptime", "运行时长"),
				K("cpu", "总核/隔离核/每核占用"),
				K("memory", "内存与大页使用（池内/池外）"),
				K("storage", "磁盘与镜像仓库占用"),
				K("hugepages", "大页内核参数与池状态"),
				K("kernel", "内核启动基线（cmdline / 运行实际 / 配置期望 三方对照）"),
				K("hardware", "硬件健康：温度/风扇/电源/SMART"),
				K("core-dumps", "崩溃转储清单（VPP/QEMU/nfvisd）"),
				K("tech-support", "诊断归档清单"),
				K("configuration", "配置查看",
					K("sessions", "candidate 持锁会话列表"),
					K("candidate", "当前持锁会话的 candidate"),
				),
			),
			K("interfaces", "接口",
				K("physical", "DPDK 物理口",
					P("<ifname>", "接口名", DynVppIfnames,
						K("detail", "驱动/MAC/MTU/队列/NUMA"),
						K("statistics", "收发包/字节/错误/drop"),
						K("sriov", "VF 列表与占用状态"),
					),
				),
				K("management", "管理口（内核侧，IP/链路）"),
			),
			K("virtual-switches", "虚拟交换机",
				P("<name>", "虚拟交换机名", DynVSwitches,
					K("detail", "类型、成员端口、VLAN/VRF 配置"),
					K("ports", "成员端口及状态/计数"),
					K("mac-table", "MAC 学习表（仅 L2）"),
					K("statistics", "每端口收发计数"),
				),
			),
			K("vrfs", "L3 虚拟交换机（VRF）",
				P("<name>", "VRF 名", DynVrfs,
					K("routes", "FIB 路由表"),
				),
			),
			K("acls", "ACL（含命中计数）",
				P("<name>", "ACL 名", DynAcls,
					K("detail", "规则与绑定详情"),
				),
			),
			K("nat", "NAT 池、规则与转换会话计数"),
			K("port-mirroring", "SPAN 会话状态"),
			K("qos", "限速策略",
				K("policies", "策略与绑定列表"),
			),
			K("vpp", "VPP 数据面",
				K("threads", "main/worker 线程清单与绑核"),
				K("runtime", "每线程向量率/指令周期",
					Opt(K("thread", "指定线程", PT("<id>", "uint", "线程 ID"))),
				),
				K("buffers", "buffer 池（每 NUMA）使用量"),
				K("memory", "main-heap 与 hugepage 占用"),
				K("capture", "抓包会话状态与已导出 pcap 清单"),
			),
			K("bonds", "链路聚合列表",
				P("<name>", "bond 名", "",
					K("detail", "成员口各自 link/LACP actor-partner 信息"),
				),
			),
			K("lldp", "LLDP",
				K("neighbors", "邻居表",
					Opt(K("interface", "按接口过滤", P("<ifname>", "接口名", DynVppIfnames))),
				),
			),
			K("virtual-machine-functions", "VM VNF",
				P("<name>", "VNF 名", DynVMs,
					K("detail", "域 XML 摘要、资源分配、NUMA"),
					K("interfaces", "vNIC：类型/MAC/socket/交换机"),
					K("statistics", "vhost-user 口计数（经 VPP）"),
					K("snapshots", "快照列表"),
				),
			),
			K("container-functions", "容器 VNF",
				P("<name>", "容器名", DynContainers,
					K("detail", "容器详情"),
					K("interfaces", "memif vNIC 列表"),
				),
			),
			K("images", "镜像仓库",
				P("<name>", "镜像名", DynImages,
					K("detail", "类型/大小/sha256/引用计数"),
				),
			),
			K("resource-pools", "资源池：总量/已分配/空闲（含 vpp-reserved）"),
			K("alarms", "告警列表",
				Opt(VE("state", "告警状态过滤", "active", "all")),
			),
			K("log", "日志",
				K("system", "系统日志",
					Opt(K("level", "按级别过滤", VE("level", "日志级别", "debug", "info", "warn", "error"))),
					Opt(K("last", "最近 N 条", PT("<n>", "uint", "条数"))),
				),
				K("audit", "审计日志",
					Opt(K("last", "最近 N 条", PT("<n>", "uint", "条数"))),
				),
				K("vnf", "VNF 控制台/事件日志",
					P("<name>", "VNF 名", DynVMs,
						Opt(K("last", "最近 N 条", PT("<n>", "uint", "条数"))),
					),
				),
			),
			K("users", "本地用户与 class"),
			K("configuration", "配置显示",
				K("candidate", "当前持锁会话的 candidate"),
				K("history", "提交历史快照：rev/时间/用户/注释/是否当前（不含配置正文）"),
				K("permissions", "按 class 视角显示",
					P("<class>", "class 名", DynClasses),
				),
			),
			K("tech-support", "诊断包清单预览"),
		),
		Op(K("request", "运维动作",
			K("virtual-machine-functions", "VM VNF 操作",
				P("<name>", "VNF 名", DynVMs,
					K("start", "启动"),
					K("stop", "停止（ACPI 关机，超时强杀）"),
					K("restart", "重启"),
					K("console", "进入串口（Ctrl-] 退出）"),
					K("snapshot", "快照操作",
						K("create", "创建快照", Opt(K("name", "快照名", PT("<name>", "name", "名称")))),
						K("rollback", "回滚快照", Opt(K("name", "快照名", PT("<name>", "name", "名称")))),
						K("delete", "删除快照", Opt(K("name", "快照名", PT("<name>", "name", "名称")))),
					),
					Su(K("delete", "删除 VNF（级联 vNIC/VPP 端口/快照）")),
				),
			),
			K("container-functions", "容器 VNF 操作",
				P("<name>", "容器名", DynContainers,
					K("start", "启动"),
					K("stop", "停止"),
					K("restart", "重启"),
					K("log", "容器 stdout/stderr",
						Opt(K("last", "最近 N 条", PT("<n>", "uint", "条数"))),
					),
					Su(K("delete", "删除容器")),
				),
			),
			K("images", "镜像管理",
				K("upload", "从 /data/incoming/ 导入",
					K("name", "镜像名", PT("<name>", "name", "名称")),
					K("type", "镜像类型", VE("type", "vm-image|container-image", "vm-image", "container-image")),
					K("file", "incoming 内的文件路径", V("path", "路径")),
				),
				K("download", "从 HTTP(S) URL 拉取（sha256 校验/断点续传）",
					K("name", "镜像名", PT("<name>", "name", "名称")),
					K("type", "镜像类型", VE("type", "vm-image|container-image", "vm-image", "container-image")),
					K("url", "下载地址", V("url", "URL")),
					Opt(K("sha256", "校验和", V("hex", "十六进制"))),
				),
				Su(K("delete", "删除镜像（引用检查后）",
					P("<name>", "镜像名", DynImages),
				)),
			),
			K("interfaces", "接口启停与驱动接管",
				// 候选取 VPP ∪ 内核：同层的 enable/disable 作用于数据面口（VPP），
				// bind-dpdk 作用于尚未接管的内核口，unbind-dpdk 常需 PCI 地址——
				// 参数位置在动作之前、无法按动作区分来源，故取并集（决策 #83）。
				P("<ifname>", "接口名", DynIfnames,
					K("enable", "启用"),
					K("disable", "禁用"),
					K("bind-dpdk", "绑定到 DPDK 驱动（缺省 vfio-pci；中断流量，需确认）",
						Opt(K("uio-driver", "用户态驱动", VE("driver", "驱动", "vfio-pci", "igb-uio"))),
					),
					K("unbind-dpdk", "解绑并交还内核驱动（中断流量，需确认）",
						Opt(K("to-driver", "交还的内核驱动（缺省交内核自动探测；实测常需显式给出）", V("string", "如 vmxnet3"))),
					),
				),
			),
			K("sriov", "SR-IOV VF 管理",
				K("create-vfs", "在物理口上创建 VF",
					P("<ifname>", "物理口", DynKernelIfnames),
					K("count", "VF 数量", PT("<uint>", "uint", "数量")),
				),
				K("delete-vfs", "回收 VF",
					P("<ifname>", "物理口", DynKernelIfnames),
					K("vf", "VF 编号", PT("<uint>", "uint", "VF ID")),
				),
			),
			Su(K("vpp", "VPP 数据面操作",
				K("restart", "按 committed 配置重建数据面并恢复收敛"),
				K("trace", "数据面抓包",
					K("start", "开始抓包",
						K("interface", "抓包接口", P("<ifname>", "接口名", DynVppIfnames)),
						Opt(K("count", "达到报文数自动停止", PT("<n>", "uint", "报文数"))),
						Opt(K("filter", "ACL 过滤", P("<acl>", "ACL 名", DynAcls))),
					),
					K("stop", "停止抓包"),
					K("export", "导出 pcap 到诊断目录", Opt(K("name", "文件名", PT("<name>", "name", "名称")))),
				),
			)),
			K("system", "系统操作",
				K("kernel", "内核启动基线",
					K("apply", "按 committed 配置写入 GRUB 基线（需重启生效）"),
					K("rollback", "回退上一次内核基线（需重启生效）"),
				),
				Su(K("software", "软件升级",
					K("add", "安装 deb 包/URL",
						PT("<deb>", "path", "deb 包路径或 URL"),
						Opt(K("sha256", "校验和", V("hex", "十六进制"))),
					),
					K("rollback", "回退到上一版本", Opt(K("to", "指定版本", V("string", "版本号")))),
				)),
				Su(K("reboot", "重启系统")),
				Su(K("shutdown", "关机")),
				Su(K("poweroff", "断电")),
				Su(K("configuration", "配置备份与恢复",
					K("backup", "导出 committed 配置归档", Opt(K("to", "目标路径", V("path", "路径")))),
					K("restore", "导入归档为 candidate 并提交", PT("<path>", "path", "归档路径")),
				)),
				K("tech-support", "诊断归档",
					K("generate", "生成诊断归档 tar.gz"),
				),
				K("core-dumps", "崩溃转储管理",
					K("export", "导出到 URL", V("url", "URL")),
					K("delete", "删除转储", Opt(K("file", "指定文件", PT("<name>", "name", "文件名")))),
				),
				Su(K("zeroize", "恢复出厂（双重确认）")),
				Su(K("api", "API 服务管理",
					K("tls", "TLS 证书",
						K("regenerate", "重签自签证书"),
					),
					K("token", "Token 管理",
						K("revoke", "吊销 token", PT("<token-id>", "name", "token ID")),
					),
				)),
				Su(K("ssh", "SSH 管理",
					K("host-key", "Host Key",
						K("regenerate", "重新生成"),
					),
				)),
				K("password", "口令",
					K("change", "登录者自助改密（验证旧口令）"),
				),
				Su(K("storage", "存储管理",
					K("format-data", "重置数据分区（危险，双确认）"),
				)),
				K("ntp", "时间同步",
					K("sync", "立即触发一次 NTP 同步"),
				),
			),
			K("alarms", "告警管理",
				K("clear", "清除已 resolved 告警",
					Opt(K("id", "指定告警", PT("<id>", "name", "告警 ID"))),
					Opt(VE("scope", "清除范围", "all")),
				),
			),
		)),
		Op(K("wizard", "初始化向导（CLI 端交互式：问答规划资源池与内核基线并提交；非 TTY 不可用）")),
		Su(K("configure", "进入配置模式（仅 super-user）")),
		Op(K("ping", "连通性测试",
			PT("<host>", "string", "目标地址"),
			Opt(K("source", "源地址", V("ip", "IP"))),
			Opt(K("count", "次数", PT("<n>", "uint", "次数"))),
			Opt(K("vrf", "经指定 VRF", P("<name>", "VRF 名", DynVrfs))),
		)),
		Op(K("traceroute", "路径跟踪",
			PT("<host>", "string", "目标地址"),
			Opt(K("vrf", "经指定 VRF", P("<name>", "VRF 名", DynVrfs))),
		)),
		Op(K("monitor", "实时监控",
			K("interfaces", "实时刷新接口计数（Ctrl-C 退出）",
				P("<ifname>", "接口名", DynVppIfnames),
				Opt(K("interval", "刷新间隔秒", PT("<sec>", "uint", "秒"))),
			),
			K("vnf", "跟踪 VNF 状态/事件（Ctrl-C 退出）",
				P("<name>", "VNF 名", DynVMs),
			),
		)),
		Su(K("clear", "清除",
			K("interfaces", "接口",
				K("statistics", "清零统计计数", Opt(P("<ifname>", "接口名", DynVppIfnames))),
			),
		)),
		Su(K("start", "启动",
			K("shell", "进入系统 shell（仅本地控制台，SSH 禁用）"),
		)),
		K("help", "帮助", Opt(PT("<command>", "string", "命令"))),
		K("exit", "退出 CLI"),
		K("quit", "退出 CLI"),
	)
	finalize(root, nil)
	return root
}
